public without sharing class CS_Businesses {
	public String ID;
	public String name;
	public Integer entityType;
	public String tin;
	public String parentCompanyIDs;
	public String dba;
	public String natureOfBusiness;
	public String establishedDate;
	public Boolean isNonProfit;
	public Integer resolutionOnFileType;
	public String principalOfficeState;
	public String principalOfficeCity;
	public CS_Address address;
	public Boolean isEngagesInInternetGambling;
	public CS_Signers[] signers;
}