public without sharing class CS_Signers {
	public String ID;
	public String firstName;
	public String middleName;
	public String lastName;
	public String suffixName;
	public CS_Address address;
	public String dateOfBirth;
	public String ssn;
	public Boolean isDocumentSigner;
	public Boolean isResolutionSigner;
	public Boolean isResolutionCertifier;
	public Boolean isBeneficialOwner;
	public Boolean isBeneficialOwnerManager;
	public Boolean isBeneficialOwnerCertifier;
	public Boolean isTINCertifier;
	public String capacityDescription;
	public Boolean isTrustee;
	public Boolean isTrustBeneficiary;
	public Boolean isTrustCreator;
}